### PR TITLE
Adding ability to use external properties file and ensuring port, time and database are integers

### PR DESCRIPTION
**Pull request by ctoestreich**

### CODE REVIEW

**Comment by mseelye** [comment]
:+1:

**Comment by ctoestreich** [comment]
Ted did some testing and had to use the following code in redis plugin.  I am not sure if groovy truth for the if(map.port) will be sufficient

``` groovy
def port = redisConfigMap.isSet("port") ? "${redisConfigMap.port}" as Integer : Protocol.DEFAULT_PORT
def timeout = redisConfigMap.isSet("timeout") ? "${redisConfigMap?.timeout}" as Integer : Protocol.DEFAULT_TIMEOUT
```

**Comment by ctoestreich** [comment]
*cough*  any update?

**Comment by ctoestreich** [comment]
@michaelcameron remember when you complained about authors not looking at pull requests?  Just saying...

**Comment by mseelye** [comment]
:laughing:

**Comment by ctoestreich** [comment]
mergeallthecode

**Comment by mseelye** [comment]
I'll just wait here

**Comment by kevana** [comment]
:+1:

**Comment by michaelcameron** [comment]
We had talked about the need for this and what I understood was this was intended to address situations where the config was represented as strings from a properties file and could not be integers like a direct `config.groovy` configuration. But the existing code already handles that case, in groovy:

```groovy
assert 123 as Integer == 123
assert "123" as Integer == 123
assert " 123 " as Integer == 123
try{
  "123foo" as Integer 
} catch(Exception e) {
  assert e.class == java.lang.NumberFormatException
  assert e.message == 'For input string: "123foo"'
}
```

The only thing the PR will do is silently use the default port/host/db if the config value is not an integer. I would much rather have it fail hard if my intended config value was not valid integer instead of silently ignoring it and using another value. And that doesn't seem to address what I thought was an issue. What am I missing?

**Comment by ctoestreich** [comment]
The defaulting behavior is your choice.  I tested the external config and it is working well.  Looks like the redis plugin was the major culprit and that has been fixed.

**Pull request closed without merging**
